### ISSUE TITLE
Feature request: reporting Sense Rate in --unpaired mode

### ISSUE THREAD

**Issue by bknisbac** [broadinstitute/rnaseqc#27]
It would be great if --unpaired would report the Sense Rate of mapping for the Single End reads. I recommend placing it into "End 1 Sense Rate" rather than making a new column unique to --unpaired mode. 

Of note, for the other End 1 & End 2 metrics there are columns that already provide the respective information. 

Thanks!

**Comment by agraubert** [comment]
Just pushed to master. This will be included in the next release of RNA-SeQC, but in the meantime, you can access this feature using the docker image `gcr.io/broad-cga-aarong-gtex/rnaseqc:98aebe7e97487669ab9bf9b1368f591a201caeaf`
