### ISSUE TITLE
Alternative to collapse transcripts

### ISSUE THREAD

**Issue by adomingues** [broadinstitute/rnaseqc#31]
I am very interested in using `RNAseq-QC` for our standard pipelines, however I ran into the issue preparing a GTF suitable for the tool. We use ensembl GTFs and the script suggested to prepare the GTF [doesn't work](https://github.com/broadinstitute/gtex-pipeline/issues/26)  for GTFs from this source. I tried to modify the GTF using `sed` to make it compatible with scritpt, but I still got an error (`KeyError: 'level'`). 

My question: 

is there is another tool / script / solution you would suggest to prepare an ensembl GTF for `RNAseq-QC`? If not it would appear that `RNAseq-QC` is limited to the annotations available from GENCODE, and therefore unsuable for anyone not working with either human or mouse (or unwilling to change the source of annotations). Is this correct? 

(I used to use `RNAseq-QC` a few years ago (JAVA versions), and iirc it worked with any gtf. Is my memory playing tricks?)

**Comment by francois-a** [comment]
Hi,

Thanks for pointing this out. We'll try to make the collapsing script compatible with ensembl GTFs.

**Comment by francois-a** [comment]
This version should work: https://github.com/broadinstitute/gtex-pipeline/blob/v9/gene_model/collapse_annotation.py (tested on the example provided at https://github.com/broadinstitute/gtex-pipeline/issues/26)

**Comment by adomingues** [comment]
Cheers @francois-a. That was fast! I will test it and report back.

**Comment by adomingues** [comment]
It worked like a charm. I also ran `rnaseqc` at it went without a glitch. Quick unrelated question (I can also create a new issue for this):

in the old JAVA versions `rnaseqc` produced an html report, but that seems to be missing now. Is that correct?

**Comment by francois-a** [comment]
Yes this is correct. However, the new version can also generate a visual report, designed to compare multiple samples. Please take a look here: https://github.com/broadinstitute/rnaseqc/tree/master/python

**Comment by joaoufrj** [comment]
Hello, the link for the collapsed_annotation.py version working with Ensembl GTF file is not working. Could you fix that?

**Comment by francois-a** [comment]
Hi, can you please provide the GTF that you're trying to collapse?

**Comment by joaoufrj** [comment]
Hi,

Please, let me know if this link download the GTF file works: https://www.dropbox.com/s/rtj44hggx3lofux/Human_vivax.gtf?dl=0

Cheers,

Joao

**Comment by francois-a** [comment]
Yes, thanks. The Plasmodium portion does not follow the [GTF format](https://www.gencodegenes.org/pages/data_format.html) definition, and only defines transcripts. You'll need to modify it (adding `gene` features and missing attributes) to work with this script.

**Comment by joaoufrj** [comment]
I see! The original plasmodium annotation file was GFF. Then I converted to gtf to combine with the ensembl gtf file. Do you think that could have affected proper reads alignment to plasmodium genome? It seemed fine when I checked with IGV but that is why I also want to run RNASeQC.

I don’t know how I can edit the gtf file to include what it needs to be collapsed using your script, so if you could please give some guidance for the right scripts, to do this changes, etc, I would appreciate it.

Cheers,

Joao

**Comment by ehenrion** [comment]
Hi,

I am having the same issue with the human b37 gtf from Ensembl v75.
I know that's an old one... but it raises the exact same issue :

`Traceback (most recent call last):
  File "gene_model/collapse_annotation.py", line 294, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "gene_model/collapse_annotation.py", line 89, in __init__
    attributes.pop('transcript_type'), g, start_pos, end_pos)
KeyError: 'transcript_type'`

My command was : 
`python ~/src/gtex-pipeline/gene_model/collapse_annotation.py Homo_sapiens.GRCh37.Ensembl75.gtf Homo_sapiens.GRCh37.Ensembl75.genes.gtf`


The same command runs fine on the human b38 gtf from Ensembl v104.

Is there a way to use the script on b37 Ensembl v75 ?

Best,
Edouard

**Comment by ehenrion** [comment]
OK, I understand why.

The b38 gtf from Ensembl contains the `transcript_biotype` feature but the b37 gtf does not.
I guess I will have to do some manual edition of my gtf to make it compatible.

Thanks for your amazing tools !

Best,
Edouard
