### ISSUE TITLE
--Unpaired option documentation 

### ISSUE THREAD

**Issue by adomingues** [broadinstitute/rnaseqc#32]
Hi @ agraubert,

I noticed a strange behaviour with some of my libraries which I managed to pin down to the  `--unpaired` option. The issue is that with single-end libraries `rnaseqc` was not reporting any counts / fpm / coverage (zeros for all entries) even though (i) the metrics files did have reasonable numbers, and (ii) STAR was reporting gene counts. 

To debug this issue I took the example dataset, converted the mapped alignments to fastq and proceeded to map either in paired mode using R1 and R2, or R1 alone in single mode:

```bash
#PE
@CO     user command line: STAR --genomeDir /projects/bioinfo/igenomes/Homo_sapiens/Ensembl_v88_custom/GRCh38/Sequence/StarIndex --readFilesIn downsampled_pe_R1.fastq.gz /lustre/projects/bioinfo/domingue/test_RNA-SeQC/alignments/downsampled_pe_R2.fastq.gz --runThreadN 6 --readFilesCommand zcat --outFileNamePrefix downsampled_pe. --outSAMtype BAM SortedByCoordinate --sjdbGTFfile /projects/bioinfo/igenomes/Homo_sapiens/Ensembl_v88_custom/GRCh38/Annotation/Genes/genes.gtf --quantMode GeneCounts --outSAMattrRGline ID:downsampled_pe PL:illumina SM:downsampled_pe

#SE
@CO     user command line: STAR --genomeDir /projects/bioinfo/igenomes/Homo_sapiens/Ensembl_v88_custom/GRCh38/Sequence/StarIndex --readFilesIn downsampled_se.fastq.gz --runThreadN 6 --readFilesCommand zcat --outFileNamePrefix downsampled_se. --outSAMtype BAM SortedByCoordinate --sjdbGTFfile /projects/bioinfo/igenomes/Homo_sapiens/Ensembl_v88_custom/GRCh38/Annotation/Genes/genes.gtf --quantMode GeneCounts --outSAMattrRGline ID:downsampled_se PL:illumina SM:downsampled_se
```

I then QC-ed these with and without setting `--unpaired`:

```bash
downsampled_pe/downsampled_pe.gene_reads.gct:ENSG00000075624    ACTB    19
downsampled_pe_unpaired/downsampled_pe.gene_reads.gct:ENSG00000075624   ACTB    19
downsampled_se/downsampled_se.gene_reads.gct:ENSG00000075624    ACTB    0
downsampled_se_unpaired/downsampled_se.gene_reads.gct:ENSG00000075624   ACTB    13
```
As you can see for that example gene PE mapping always reports counts, however SE only works with the unpaired flag set. It was not clear to me from the help that this flag needs to be set for SE end data:

> -u, --unpaired                    Treat all reads as unpaired, ignoring
>                                     filters which require properly paired
>                                     reads

I would like to ask if either:

a) it could be made clearer in the help docs that this must be set for single end data, and / or
b) `rnaseq` would detect if the alignments are single end and proceed accordingly.

Cheers,
António

**Comment by agraubert** [comment]
Thanks for reporting this António! This does indeed look like poor documentation. The `--unpaired` option disables the requirement that reads have a mate to be quantified, which would be required for single end libraries. I will update the documentation

**Comment by adomingues** [comment]
Cheers @agraubert!

**Comment by agraubert** [comment]
I've pushed a [new release](https://github.com/broadinstitute/rnaseqc/releases/tag/v2.3.5) containing this fix. The precompiled binaries should be available on the releases page in about 20 minutes from now.

If you use the docker image, you can use `gcr.io/broad-cga-aarong-gtex/rnaseqc:2.3.5`
